<?php

use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder {

    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Master',
                'icon' => 'la la-archive',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-08-25 04:13:00',
                'updated_at' => '2020-08-25 04:13:00',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Kontributor',
                'icon' => NULL,
                'url' => 'admin/contributor',
                'parent_id' => 1,
                'created_at' => '2020-08-25 04:13:26',
                'updated_at' => '2020-08-25 04:13:26',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Kategori',
                'icon' => NULL,
                'url' => 'admin/category',
                'parent_id' => 1,
                'created_at' => '2020-08-25 04:13:54',
                'updated_at' => '2020-08-25 04:13:54',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Subjek',
                'icon' => NULL,
                'url' => 'admin/subject',
                'parent_id' => 1,
                'created_at' => '2020-08-25 04:14:05',
                'updated_at' => '2020-08-25 04:14:05',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Masalah',
                'icon' => NULL,
                'url' => 'admin/problem',
                'parent_id' => 1,
                'created_at' => '2020-08-25 04:14:22',
                'updated_at' => '2020-08-25 04:14:22',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Provinsi',
                'icon' => NULL,
                'url' => 'admin/province',
                'parent_id' => 1,
                'created_at' => '2020-08-25 04:14:34',
                'updated_at' => '2020-08-25 04:14:34',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Kota / Kabupaten',
                'icon' => NULL,
                'url' => 'admin/city',
                'parent_id' => 1,
                'created_at' => '2020-08-25 04:14:47',
                'updated_at' => '2020-11-26 20:08:53',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Kecamatan',
                'icon' => NULL,
                'url' => 'admin/district',
                'parent_id' => 1,
                'created_at' => '2020-08-25 04:15:12',
                'updated_at' => '2020-08-25 04:15:12',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Kelurahan',
                'icon' => NULL,
                'url' => 'admin/village',
                'parent_id' => 1,
                'created_at' => '2020-08-25 04:15:23',
                'updated_at' => '2020-08-25 04:15:23',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Buku',
                'icon' => 'la la-book',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-08-25 04:15:39',
                'updated_at' => '2020-08-25 04:15:39',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Masalah',
                'icon' => NULL,
                'url' => 'admin/collection/problem/1',
                'parent_id' => 10,
                'created_at' => '2020-08-25 04:17:03',
                'updated_at' => '2020-09-24 21:08:04',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Pemantauan',
                'icon' => NULL,
                'url' => 'admin/collection/monitoring/1',
                'parent_id' => 10,
                'created_at' => '2020-08-25 04:17:17',
                'updated_at' => '2020-09-24 21:08:17',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Pengelolaan',
                'icon' => NULL,
                'url' => 'admin/collection/manage/1',
                'parent_id' => 10,
                'created_at' => '2020-08-25 04:17:40',
                'updated_at' => '2020-09-24 21:08:27',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Koleksi Serial',
                'icon' => 'la la-list-alt',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-11-18 12:17:06',
                'updated_at' => '2020-11-18 12:17:41',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Status Bermasalah',
                'icon' => NULL,
                'url' => 'publisher/collection/problem/4',
                'parent_id' => 14,
                'created_at' => '2020-11-18 12:18:35',
                'updated_at' => '2020-11-18 12:20:02',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Status Direview',
                'icon' => NULL,
                'url' => 'publisher/collection/monitoring/4',
                'parent_id' => 14,
                'created_at' => '2020-11-18 12:18:52',
                'updated_at' => '2020-11-18 12:20:35',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Partitur',
                'icon' => 'la la-file-audio-o',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-08-25 04:19:40',
                'updated_at' => '2020-08-25 04:19:40',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Peta',
                'icon' => 'la la-map',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-08-25 04:19:57',
                'updated_at' => '2020-08-25 04:19:57',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Serial',
                'icon' => 'la la-list-alt',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-08-25 04:20:14',
                'updated_at' => '2020-08-25 04:20:14',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Audio',
                'icon' => 'la la-music',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-08-25 04:20:37',
                'updated_at' => '2020-08-25 04:20:37',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Film',
                'icon' => 'la la-film',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-08-25 04:20:52',
                'updated_at' => '2020-08-25 04:20:52',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Penerbit',
                'icon' => 'la la-user-secret',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-08-25 04:21:05',
                'updated_at' => '2020-08-25 04:21:05',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Tagihan ISBN',
                'icon' => 'la la-credit-card',
                'url' => 'admin/bill_isbn',
                'parent_id' => 0,
                'created_at' => '2020-08-25 04:21:21',
                'updated_at' => '2020-10-03 22:48:51',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Artikel',
                'icon' => 'la la-file-text',
                'url' => 'admin/article',
                'parent_id' => 0,
                'created_at' => '2020-08-25 04:21:35',
                'updated_at' => '2020-08-25 13:45:11',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Laporan',
                'icon' => 'la la-bar-chart',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-08-25 04:21:51',
                'updated_at' => '2020-08-25 04:21:51',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Pengaturan',
                'icon' => 'la la-cog',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-08-25 04:22:06',
                'updated_at' => '2020-08-25 04:22:06',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Masalah',
                'icon' => NULL,
                'url' => 'admin/collection/problem/2',
                'parent_id' => 17,
                'created_at' => '2020-08-25 04:23:11',
                'updated_at' => '2020-09-24 19:38:33',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Pemantauan',
                'icon' => NULL,
                'url' => 'admin/collection/monitoring/2',
                'parent_id' => 17,
                'created_at' => '2020-08-25 04:23:26',
                'updated_at' => '2020-09-24 19:39:11',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Pengelolaan',
                'icon' => NULL,
                'url' => 'admin/collection/manage/2',
                'parent_id' => 17,
                'created_at' => '2020-08-25 04:23:36',
                'updated_at' => '2020-09-24 19:38:01',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Masalah',
                'icon' => NULL,
                'url' => 'admin/collection/problem/3',
                'parent_id' => 18,
                'created_at' => '2020-08-25 04:23:47',
                'updated_at' => '2020-09-24 19:38:29',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Pemantauan',
                'icon' => NULL,
                'url' => 'admin/collection/monitoring/3',
                'parent_id' => 18,
                'created_at' => '2020-08-25 04:24:09',
                'updated_at' => '2020-09-24 19:39:07',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Pengelolaan',
                'icon' => NULL,
                'url' => 'admin/collection/manage/3',
                'parent_id' => 18,
                'created_at' => '2020-08-25 04:24:20',
                'updated_at' => '2020-09-24 19:37:55',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Masalah',
                'icon' => NULL,
                'url' => 'admin/collection/problem/4',
                'parent_id' => 19,
                'created_at' => '2020-08-25 04:24:52',
                'updated_at' => '2020-09-24 19:38:26',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Pemantauan',
                'icon' => NULL,
                'url' => 'admin/collection/monitoring/4',
                'parent_id' => 19,
                'created_at' => '2020-08-25 04:25:06',
                'updated_at' => '2020-09-24 19:39:01',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Pengelolaan',
                'icon' => NULL,
                'url' => 'admin/collection/manage/4',
                'parent_id' => 19,
                'created_at' => '2020-08-25 04:25:16',
                'updated_at' => '2020-09-24 19:37:52',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Masalah',
                'icon' => NULL,
                'url' => 'admin/collection/problem/5',
                'parent_id' => 20,
                'created_at' => '2020-08-25 04:25:29',
                'updated_at' => '2020-09-24 19:38:22',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Pemantauan',
                'icon' => NULL,
                'url' => 'admin/collection/monitoring/5',
                'parent_id' => 20,
                'created_at' => '2020-08-25 04:25:44',
                'updated_at' => '2020-09-24 19:38:58',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Pengelolaan',
                'icon' => NULL,
                'url' => 'admin/collection/manage/5',
                'parent_id' => 20,
                'created_at' => '2020-08-25 04:25:56',
                'updated_at' => '2020-09-24 19:37:48',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Masalah',
                'icon' => NULL,
                'url' => 'admin/collection/problem/6',
                'parent_id' => 21,
                'created_at' => '2020-08-25 04:26:12',
                'updated_at' => '2020-09-24 19:38:19',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Pemantauan',
                'icon' => NULL,
                'url' => 'admin/collection/monitoring/6',
                'parent_id' => 21,
                'created_at' => '2020-08-25 04:26:23',
                'updated_at' => '2020-09-24 19:38:55',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Pengelolaan',
                'icon' => NULL,
                'url' => 'admin/collection/manage/6',
                'parent_id' => 21,
                'created_at' => '2020-08-25 04:26:36',
                'updated_at' => '2020-09-24 19:37:45',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Koleksi',
                'icon' => NULL,
                'url' => 'admin/report/collection',
                'parent_id' => 25,
                'created_at' => '2020-08-25 04:27:15',
                'updated_at' => '2020-08-25 04:27:15',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Status Diterima',
                'icon' => NULL,
                'url' => 'publisher/collection/accepted/4',
                'parent_id' => 14,
                'created_at' => '2020-11-18 12:19:16',
                'updated_at' => '2020-11-18 12:20:46',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 45,
                'name' => 'Penerbit',
                'icon' => NULL,
                'url' => 'admin/report/publisher',
                'parent_id' => 25,
                'created_at' => '2020-08-25 04:28:14',
                'updated_at' => '2020-09-08 20:50:51',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 46,
                'name' => 'Log Aktivitas',
                'icon' => NULL,
                'url' => 'admin/report/log_activity',
                'parent_id' => 25,
                'created_at' => '2020-08-25 04:28:32',
                'updated_at' => '2020-08-25 04:28:32',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 47,
                'name' => 'User',
                'icon' => NULL,
                'url' => 'admin/setting/user',
                'parent_id' => 26,
                'created_at' => '2020-08-25 04:28:53',
                'updated_at' => '2020-08-25 04:28:53',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 48,
                'name' => 'Role',
                'icon' => NULL,
                'url' => 'admin/setting/role',
                'parent_id' => 26,
                'created_at' => '2020-08-25 04:29:06',
                'updated_at' => '2020-08-25 20:43:41',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 49,
                'name' => 'Menu',
                'icon' => NULL,
                'url' => 'admin/setting/menu',
                'parent_id' => 26,
                'created_at' => '2020-08-25 04:29:26',
                'updated_at' => '2020-08-25 04:29:26',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 50,
                'name' => 'Syarat & Ketentuan',
                'icon' => NULL,
                'url' => 'admin/setting/term_condition',
                'parent_id' => 26,
                'created_at' => '2020-08-25 04:29:44',
                'updated_at' => '2020-08-25 04:29:44',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 51,
                'name' => 'Tentang Kami',
                'icon' => NULL,
                'url' => 'admin/setting/about_me',
                'parent_id' => 26,
                'created_at' => '2020-08-25 04:29:58',
                'updated_at' => '2020-08-25 04:29:58',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 55,
                'name' => 'Pemantauan',
                'icon' => NULL,
                'url' => 'admin/publisher/monitoring',
                'parent_id' => 22,
                'created_at' => '2020-08-25 13:54:27',
                'updated_at' => '2020-08-25 13:54:27',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 56,
                'name' => 'Pengelolaan',
                'icon' => NULL,
                'url' => 'admin/publisher/manage',
                'parent_id' => 22,
                'created_at' => '2020-08-25 13:54:38',
                'updated_at' => '2020-08-25 13:54:38',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 57,
                'name' => 'Author',
                'icon' => NULL,
                'url' => 'admin/author',
                'parent_id' => 1,
                'created_at' => '2020-08-26 17:46:11',
                'updated_at' => '2020-08-26 17:46:11',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 58,
                'name' => 'Entri',
                'icon' => NULL,
                'url' => 'admin/collection/create_manual/1',
                'parent_id' => 10,
                'created_at' => '2020-09-04 19:45:00',
                'updated_at' => '2020-09-24 19:40:04',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 59,
                'name' => 'Entri',
                'icon' => NULL,
                'url' => 'admin/collection/create_manual/2',
                'parent_id' => 17,
                'created_at' => '2020-09-04 19:45:15',
                'updated_at' => '2020-09-24 19:40:01',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 60,
                'name' => 'Entri',
                'icon' => NULL,
                'url' => 'admin/collection/create_manual/3',
                'parent_id' => 18,
                'created_at' => '2020-09-04 19:45:55',
                'updated_at' => '2020-09-24 19:39:57',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 61,
                'name' => 'Entri',
                'icon' => NULL,
                'url' => 'admin/collection/create_manual/4',
                'parent_id' => 19,
                'created_at' => '2020-09-04 19:46:11',
                'updated_at' => '2020-09-24 19:39:55',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 62,
                'name' => 'Entri',
                'icon' => NULL,
                'url' => 'admin/collection/create_manual/5',
                'parent_id' => 20,
                'created_at' => '2020-09-04 19:46:24',
                'updated_at' => '2020-09-24 19:39:50',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 63,
                'name' => 'Entri',
                'icon' => NULL,
                'url' => 'admin/collection/create_manual/6',
                'parent_id' => 21,
                'created_at' => '2020-09-04 19:46:38',
                'updated_at' => '2020-09-24 19:39:47',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 64,
                'name' => 'Entri',
                'icon' => NULL,
                'url' => 'admin/publisher/create',
                'parent_id' => 22,
                'created_at' => '2020-09-21 19:21:32',
                'updated_at' => '2020-09-21 19:21:32',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 65,
                'name' => 'Template Email',
                'icon' => NULL,
                'url' => 'admin/report/email',
                'parent_id' => 26,
                'created_at' => '2020-09-23 18:42:14',
                'updated_at' => '2020-09-23 18:42:14',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 68,
                'name' => 'File Download',
                'icon' => NULL,
                'url' => 'admin/report/file_download',
                'parent_id' => 25,
                'created_at' => '2020-10-04 22:25:47',
                'updated_at' => '2020-10-04 22:25:47',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 69,
                'name' => 'Organisasi',
                'icon' => NULL,
                'url' => 'admin/organization',
                'parent_id' => 1,
                'created_at' => '2020-10-06 18:23:41',
                'updated_at' => '2020-10-06 23:14:40',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 70,
                'name' => 'Template Email',
                'icon' => 'la la-envelope',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-10-11 21:00:06',
                'updated_at' => '2020-10-11 21:00:06',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 71,
                'name' => 'Aktivasi',
                'icon' => NULL,
                'url' => 'admin/template_email/activation',
                'parent_id' => 70,
                'created_at' => '2020-10-11 21:11:45',
                'updated_at' => '2020-10-11 21:11:45',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 72,
                'name' => 'Ganti Password',
                'icon' => NULL,
                'url' => 'admin/template_email/change_password',
                'parent_id' => 70,
                'created_at' => '2020-10-11 21:12:11',
                'updated_at' => '2020-10-11 21:16:39',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 73,
                'name' => 'Penerbit Pengajuan',
                'icon' => NULL,
                'url' => 'admin/template_email/publisher_submission',
                'parent_id' => 70,
                'created_at' => '2020-10-11 21:12:53',
                'updated_at' => '2020-10-11 21:17:44',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 74,
                'name' => 'Koleksi Tervalidasi',
                'icon' => NULL,
                'url' => 'admin/template_email/collection_success',
                'parent_id' => 70,
                'created_at' => '2020-10-11 21:13:49',
                'updated_at' => '2020-10-11 21:18:15',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 75,
                'name' => 'Koleksi Bermasalah',
                'icon' => NULL,
                'url' => 'admin/template_email/collection_problem',
                'parent_id' => 70,
                'created_at' => '2020-10-11 21:14:04',
                'updated_at' => '2020-10-11 21:18:26',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 76,
                'name' => 'Koleksi Diserahkan',
                'icon' => NULL,
                'url' => 'admin/template_email/collection_submitted',
                'parent_id' => 70,
                'created_at' => '2020-10-11 21:14:28',
                'updated_at' => '2020-10-11 21:18:50',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 77,
                'name' => 'Penerbit Tervalidasi',
                'icon' => NULL,
                'url' => 'admin/template_email/publisher_success',
                'parent_id' => 70,
                'created_at' => '2020-10-11 21:14:45',
                'updated_at' => '2020-10-11 21:19:12',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 78,
                'name' => 'Penerbit Ditolak',
                'icon' => NULL,
                'url' => 'admin/template_email/publisher_rejected',
                'parent_id' => 70,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 79,
                'name' => 'Penyerahan Koleksi',
                'icon' => 'la la-database',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 80,
                'name' => 'Unggah Banyak',
                'icon' => NULL,
                'url' => 'publisher/collection/import',
                'parent_id' => 79,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 81,
                'name' => 'Unggah Tunggal',
                'icon' => NULL,
                'url' => 'publisher/collection/create_manual',
                'parent_id' => 79,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 82,
                'name' => 'Koleksi Buku',
                'icon' => 'la la-book',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 83,
                'name' => 'Status Bermasalah',
                'icon' => NULL,
                'url' => 'publisher/collection/problem/1',
                'parent_id' => 82,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 84,
                'name' => 'Status Direview',
                'icon' => NULL,
                'url' => 'publisher/collection/monitoring/1',
                'parent_id' => 82,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 85,
                'name' => 'Status Diterima',
                'icon' => NULL,
                'url' => 'publisher/collection/accepted/1',
                'parent_id' => 82,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 86,
                'name' => 'Koleksi Partitur',
                'icon' => 'la la-file-audio-o',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 87,
                'name' => 'Status Bermasalah',
                'icon' => NULL,
                'url' => 'publisher/collection/problem/2',
                'parent_id' => 86,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 88,
                'name' => 'Status Direview',
                'icon' => NULL,
                'url' => 'publisher/collection/monitoring/2',
                'parent_id' => 86,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 89,
                'name' => 'Status Diterima',
                'icon' => NULL,
                'url' => 'publisher/collection/accepted/2',
                'parent_id' => 86,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 90,
                'name' => 'Koleksi Peta',
                'icon' => 'la la-map',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 91,
                'name' => 'Status Bermasalah',
                'icon' => NULL,
                'url' => 'publisher/collection/problem/3',
                'parent_id' => 90,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 92,
                'name' => 'Status Direview',
                'icon' => NULL,
                'url' => 'publisher/collection/monitoring/3',
                'parent_id' => 90,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 93,
                'name' => 'Status Diterima',
                'icon' => NULL,
                'url' => 'publisher/collection/accepted/3',
                'parent_id' => 90,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 95,
                'name' => 'Koleksi Audio',
                'icon' => 'la la-music',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 96,
                'name' => 'Status Bermasalah',
                'icon' => NULL,
                'url' => 'publisher/collection/problem/5',
                'parent_id' => 95,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 97,
                'name' => 'Status Direview',
                'icon' => NULL,
                'url' => 'publisher/collection/monitoring/5',
                'parent_id' => 95,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 98,
                'name' => 'Status Diterima',
                'icon' => NULL,
                'url' => 'publisher/collection/accepted/5',
                'parent_id' => 95,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 99,
                'name' => 'Koleksi Film',
                'icon' => 'la la-film',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 100,
                'name' => 'Status Bermasalah',
                'icon' => NULL,
                'url' => 'publisher/collection/problem/6',
                'parent_id' => 99,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 101,
                'name' => 'Status Direview',
                'icon' => NULL,
                'url' => 'publisher/collection/monitoring/6',
                'parent_id' => 99,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 102,
                'name' => 'Status Diterima',
                'icon' => NULL,
                'url' => 'publisher/collection/accepted/6',
                'parent_id' => 99,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 103,
                'name' => 'Data Tagihan ISBN',
                'icon' => 'la la-credit-card',
                'url' => 'publisher/bill_isbn',
                'parent_id' => 0,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 104,
                'name' => 'Permintaan File Master',
                'icon' => 'la la-folder',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 105,
                'name' => 'Permintaan Baru',
                'icon' => NULL,
                'url' => 'publisher/collection/request',
                'parent_id' => 104,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 106,
                'name' => 'Status Permintaan',
                'icon' => NULL,
                'url' => 'publisher/collection/request/monitor',
                'parent_id' => 104,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-11-09 15:06:39',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 107,
                'name' => 'Data Laporan',
                'icon' => 'la la-bar-chart',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-08-25 04:21:51',
                'updated_at' => '2020-08-25 04:21:51',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 108,
                'name' => 'Koleksi',
                'icon' => NULL,
                'url' => 'publisher/report/collection',
                'parent_id' => 107,
                'created_at' => '2020-10-11 21:14:56',
                'updated_at' => '2020-10-11 21:19:37',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 109,
                'name' => 'Request File Master',
                'icon' => 'la la-folder',
                'url' => 'admin/collection/request',
                'parent_id' => 0,
                'created_at' => '2020-11-05 19:28:46',
                'updated_at' => '2020-11-09 15:10:35',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 110,
                'name' => 'Permintaan baru',
                'icon' => NULL,
                'url' => '/admin/collection/request',
                'parent_id' => 109,
                'created_at' => '2020-11-05 19:30:01',
                'updated_at' => '2020-11-09 15:09:35',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 117,
                'name' => 'File Download',
                'icon' => NULL,
                'url' => 'publisher/report/file_download',
                'parent_id' => 107,
                'created_at' => '2020-11-18 12:22:11',
                'updated_at' => '2020-11-18 12:22:11',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 118,
                'name' => 'Pekan Penghargaan',
                'icon' => NULL,
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-11-19 18:04:59',
                'updated_at' => '2020-11-19 18:45:15',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 119,
                'name' => 'Koleksi',
                'icon' => NULL,
                'url' => 'admin/guest',
                'parent_id' => 118,
                'created_at' => '2020-11-19 18:06:05',
                'updated_at' => '2020-11-19 18:06:05',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 120,
                'name' => 'Pekan Penghargaan',
                'icon' => 'la la-flag',
                'url' => 'admin/guest',
                'parent_id' => 0,
                'created_at' => '2020-11-19 18:45:57',
                'updated_at' => '2020-11-19 18:47:24',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 121,
                'name' => 'Koleksi diserahkan',
                'icon' => 'la la-database',
                'url' => NULL,
                'parent_id' => 0,
                'created_at' => '2020-11-19 18:45:57',
                'updated_at' => '2020-11-19 18:47:24',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 122,
                'name' => 'Status Direview',
                'icon' => NUll,
                'url' => 'publisher/collection/monitoring',
                'parent_id' => 121,
                'created_at' => '2020-11-19 18:45:57',
                'updated_at' => '2020-11-19 18:47:24',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 123,
                'name' => 'Status Diterima',
                'icon' => NUll,
                'url' => 'publisher/collection/accepted',
                'parent_id' => 121,
                'created_at' => '2020-11-19 18:45:57',
                'updated_at' => '2020-11-19 18:47:24',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 124,
                'name' => 'Status Bermasalah',
                'icon' => NUll,
                'url' => 'publisher/collection/problem',
                'parent_id' => 121,
                'created_at' => '2020-11-19 18:45:57',
                'updated_at' => '2020-11-19 18:47:24',
                'deleted_at' => NULL,
            ),
             110 => 
            array (
                'id' => 124,
                'name' => 'Unggah ISBN',
                'icon' => NUll,
                'url' => 'publisher/collection/isbn',
                'parent_id' => 121,
                'created_at' => '2020-11-19 18:45:57',
                'updated_at' => '2020-11-19 18:47:24',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }

}
